/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Game;

import java.io.File;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.swing.JOptionPane;

/**
 *
 * @author Mohammed
 */
public class mainMenu extends javax.swing.JFrame {
    
    Clip clip;
    boolean isBack;
    int WIDTH = 1280;
    int HEIGHT = 720;
    long MusicFlag;
    AudioInputStream audiofile;
    
    public mainMenu() {
        initComponents();
        
        PLAY_BTN.setOpaque(false);
        PLAY_BTN.setContentAreaFilled(false);
        PLAY_BTN.setBorderPainted(false);
        
        SCOREBOARD_BTN.setOpaque(false);
        SCOREBOARD_BTN.setContentAreaFilled(false);
        SCOREBOARD_BTN.setBorderPainted(false);
        
        INSTRUCTION_BTN.setOpaque(false);
        INSTRUCTION_BTN.setContentAreaFilled(false);
        INSTRUCTION_BTN.setBorderPainted(false);
        
        EXIT_BTN.setOpaque(false);
        EXIT_BTN.setContentAreaFilled(false);
        EXIT_BTN.setBorderPainted(false);
        
        MUTE_BTN.setOpaque(false);
        MUTE_BTN.setContentAreaFilled(false);
        MUTE_BTN.setBorderPainted(false);
        
        UNMUTE_BTN.setOpaque(false);
        UNMUTE_BTN.setContentAreaFilled(false);
        UNMUTE_BTN.setBorderPainted(false);
        
        setSize(WIDTH, HEIGHT);
        jLabel1.setSize(WIDTH, HEIGHT);
        jPanel1.setSize(WIDTH, HEIGHT);
        
        setTitle("Connect4 - Main Menu");
        if (!isBack) {
            play_music();
            
        }
        setLocationRelativeTo(null);
//        setVisible(true);
//        setFocusable(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        PLAY_BTN = new javax.swing.JButton();
        SCOREBOARD_BTN = new javax.swing.JButton();
        INSTRUCTION_BTN = new javax.swing.JButton();
        EXIT_BTN = new javax.swing.JButton();
        MUTE_BTN = new javax.swing.JButton();
        UNMUTE_BTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 720));
        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/menu.jpeg"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(1280, 720));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1280, 720);

        PLAY_BTN.setText("jButton1");
        PLAY_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PLAY_BTNActionPerformed(evt);
            }
        });
        jPanel1.add(PLAY_BTN);
        PLAY_BTN.setBounds(493, 135, 220, 70);

        SCOREBOARD_BTN.setText("jButton2");
        SCOREBOARD_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SCOREBOARD_BTNActionPerformed(evt);
            }
        });
        jPanel1.add(SCOREBOARD_BTN);
        SCOREBOARD_BTN.setBounds(493, 210, 230, 80);

        INSTRUCTION_BTN.setText("jButton3");
        INSTRUCTION_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                INSTRUCTION_BTNActionPerformed(evt);
            }
        });
        jPanel1.add(INSTRUCTION_BTN);
        INSTRUCTION_BTN.setBounds(493, 290, 230, 80);

        EXIT_BTN.setText("jButton4");
        EXIT_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EXIT_BTNActionPerformed(evt);
            }
        });
        jPanel1.add(EXIT_BTN);
        EXIT_BTN.setBounds(493, 370, 230, 80);

        MUTE_BTN.setText("jButton5");
        MUTE_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MUTE_BTNActionPerformed(evt);
            }
        });
        jPanel1.add(MUTE_BTN);
        MUTE_BTN.setBounds(1143, 30, 70, 70);

        UNMUTE_BTN.setText("jButton6");
        UNMUTE_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UNMUTE_BTNActionPerformed(evt);
            }
        });
        jPanel1.add(UNMUTE_BTN);
        UNMUTE_BTN.setBounds(1053, 30, 80, 70);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1280, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PLAY_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PLAY_BTNActionPerformed
        // TODO add your handling code here:
        try {
            System.out.println("FROM SCOREBOARD TO MENUE");
//            clip.stop();
            mainMenu.this.setVisible(false);
            play play_page = new play();
            play_page.setVisible(true);
        } catch (Exception e) {
            
        }
        
    }//GEN-LAST:event_PLAY_BTNActionPerformed

    private void SCOREBOARD_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SCOREBOARD_BTNActionPerformed
        // TODO add your handling code here:
        try {
            System.out.println("FROM MENU TO SCOREBOARD");
//            clip.stop();
            mainMenu.this.setVisible(false);
            scoreBoard scores_page = new scoreBoard();
            scores_page.setVisible(true);
        } catch (Exception e) {

        }
        
    }//GEN-LAST:event_SCOREBOARD_BTNActionPerformed

    private void INSTRUCTION_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_INSTRUCTION_BTNActionPerformed
        // TODO add your handling code here:
        try {
            System.out.println("FROM MENU TO INSTRUCTIONS");
//            clip.stop();
            mainMenu.this.setVisible(false);
            instructions instructions_page = new instructions();
            instructions_page.setVisible(true);
        } catch (Exception e) {
            
        }
        
        
    }//GEN-LAST:event_INSTRUCTION_BTNActionPerformed

    private void EXIT_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EXIT_BTNActionPerformed
        // TODO add your handling code here:
        try {
            System.out.println("HOOOOOOOOOOOOOOOOOOOOOOOOOME");
            clip.stop();
            System.exit(0);
            } catch (Exception e) {
            
        }
        
    }//GEN-LAST:event_EXIT_BTNActionPerformed

    private void MUTE_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MUTE_BTNActionPerformed
        // TODO add your handling code here:
        mute();
        
    }//GEN-LAST:event_MUTE_BTNActionPerformed

    private void UNMUTE_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UNMUTE_BTNActionPerformed
        // TODO add your handling code here:
            unMute();
        
    }//GEN-LAST:event_UNMUTE_BTNActionPerformed
    public void play_music()  {
        try {
            audiofile = AudioSystem.getAudioInputStream(new File("Run_Amok.wav").getAbsoluteFile());
            clip = AudioSystem.getClip();
            clip.open(audiofile);
            clip.start();
            clip.loop(Clip.LOOP_CONTINUOUSLY);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getLocalizedMessage());

        }
    }
    
    public void mute() {
        try {
            System.out.println("MUTE MUSIC");
            clip.stop();
        } catch (Exception e) {
            
        }
    
    }
    
    public void unMute() {
        try {
            System.out.println("UNMUTE MUSIC");
            MusicFlag = clip.getMicrosecondPosition();
            clip.stop();
            clip.setMicrosecondPosition(MusicFlag);
            clip.start();
            clip.loop(Clip.LOOP_CONTINUOUSLY);

        } catch (Exception e) {
                
        }
   
    
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EXIT_BTN;
    private javax.swing.JButton INSTRUCTION_BTN;
    private javax.swing.JButton MUTE_BTN;
    private javax.swing.JButton PLAY_BTN;
    private javax.swing.JButton SCOREBOARD_BTN;
    private javax.swing.JButton UNMUTE_BTN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
