/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Game;

/**
 *
 * @author Mohammed
 */
public class play extends javax.swing.JFrame {

    int WIDTH = 1280;
    int HEIGHT = 720;
    public play() {
        initComponents();
        
        
        setSize(WIDTH, HEIGHT);
        jLabel1.setSize(WIDTH, HEIGHT);
        jPanel1.setSize(WIDTH, HEIGHT);
        
        BACK_BTN.setOpaque(false);
        BACK_BTN.setContentAreaFilled(false);
        BACK_BTN.setBorderPainted(false);
        
        ONEPLAYER_BTN.setOpaque(false);
        ONEPLAYER_BTN.setContentAreaFilled(false);
        ONEPLAYER_BTN.setBorderPainted(false);
        
        TWOPLAYER_BTN.setOpaque(false);
        TWOPLAYER_BTN.setContentAreaFilled(false);
        TWOPLAYER_BTN.setBorderPainted(false);
        
        setTitle("CONNET4 - PLAY");
        
        setLocationRelativeTo(null);
//        setVisible(true);
//        setFocusable(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ONEPLAYER_BTN = new javax.swing.JButton();
        TWOPLAYER_BTN = new javax.swing.JButton();
        BACK_BTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1280, 720));

        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 720));
        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/play.jpeg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1280, 720);

        ONEPLAYER_BTN.setText("jButton1");
        ONEPLAYER_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ONEPLAYER_BTNActionPerformed(evt);
            }
        });
        jPanel1.add(ONEPLAYER_BTN);
        ONEPLAYER_BTN.setBounds(490, 230, 220, 70);

        TWOPLAYER_BTN.setText("jButton2");
        TWOPLAYER_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TWOPLAYER_BTNActionPerformed(evt);
            }
        });
        jPanel1.add(TWOPLAYER_BTN);
        TWOPLAYER_BTN.setBounds(493, 305, 250, 60);

        BACK_BTN.setText("jButton3");
        BACK_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BACK_BTNActionPerformed(evt);
            }
        });
        jPanel1.add(BACK_BTN);
        BACK_BTN.setBounds(483, 370, 290, 70);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 219, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BACK_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BACK_BTNActionPerformed
        // TODO add your handling code here:
            try {
                System.out.println("FROM PLAY TO MENUE");
                play.this.setVisible(false);
                mainMenu menu_page = new mainMenu();
                menu_page.setVisible(true);
            } catch (Exception e) {

            }
    }//GEN-LAST:event_BACK_BTNActionPerformed

    private void ONEPLAYER_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ONEPLAYER_BTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ONEPLAYER_BTNActionPerformed

    private void TWOPLAYER_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TWOPLAYER_BTNActionPerformed
        // TODO add your handling code here:
        try {
            System.out.println("FROM PLAY TO LEVELS");
            play.this.setVisible(false);
            levels levels_page = new levels();
            levels_page.setVisible(true);
        } catch (Exception e) {
            
        }
      
    }//GEN-LAST:event_TWOPLAYER_BTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(play.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(play.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(play.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(play.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new play().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BACK_BTN;
    private javax.swing.JButton ONEPLAYER_BTN;
    private javax.swing.JButton TWOPLAYER_BTN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
